name: CD

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Install pnpm and Node.js
        uses: pnpm/setup@v2
        with:
          version: 11
          runtime: node@24
          cache: true
      - name: Test and publish
        run: pnpm publish --provenance
