name: CD

on:
  workflow_dispatch:
  push:
    tags:
      - "*"

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v4
      - name: Publish
        id: publish
        uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_TOKEN }}
      - if: ${{ steps.publish.outputs.type }}
        run: |
          echo "Published version: ${{ steps.publish.outputs.version }}"
